import './globals.css'
import { Inter } from 'next/font/google'
import  GoogleAnalytics from './_components/web-vitals.js'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Foto Pork Colombia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleAnalytics GA_TRAKING_ID={process.env.GA_TRAKING_ID} />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
